### ISSUE TITLE
Disposing PooledDictionary doesn't dispose PooledList stored as values

### ISSUE THREAD

**Issue by DmitryNaumov** [jtmueller/Collections.Pooled#31]
In the following code stored lists are not returned to the pool:

```
var lookup = new PooledDictionary<int, PooledList<string>>(clearMode: ClearMode.Always);

// add values to collection...

lookup.Dispose();
```

**Comment by jtmueller** [comment]
This isn't just about PooledDictionary. None of the collection types check to see if the values implement `IDisposable` (also true of System.Collections.Generic). You think that we should test to see if the value type implements `IDisposable`, and loop through the items being returned to the pool to call Dispose on them? What if the items in question are stored in multiple places, and the user wants to discard a list or a dictionary without disposing of the items inside, because those items are still in use?

That seems like it could be dangerous and undesired behavior in some cases. What I've done in my own code in similar cases is just manually dispose the collection values before disposing the collection, in cases where I know the collection values aren't still in use anywhere else.

```csharp
lookup.Values.ForEach(v => v.Dispose());
lookup.Dispose();
```

If we do add the ability to auto-dispose collection values to all collection types, then we have to add the ability to turn off that behavior in cases where the same value is in multiple collections and so forth. I'm not entirely convinced that the extra work to manage it oneself is worth all that.

**Comment by DmitryNaumov** [comment]
I hear you, it makes sense. Thank you!
