### ISSUE TITLE
Memory analysis on on dict benchmarks, like it wad did for list.

### ISSUE THREAD

**Issue by dzmitry-lahoda** [jtmueller/Collections.Pooled#6]
There is not enough external observation for developers to start using dictionary as replacement.

**Comment by jtmueller** [comment]
@dzmitry-lahoda  What are you looking for, specifically? I took the memory analyzer off of the get/tryget/contains benchmarks because the amount of memory allocated was flat-zero across the board for both Dictionary and PooledDictionary. Having them on there just made for extra-wide tables that were harder to read and added nothing useful. 

Are you suggesting I put the memory analysis back on and re-run the benchmarks for peace of mind, or is there a specific benchmark test you think should be present but is not?

**Comment by dzmitry-lahoda** [comment]
I suggest to put data into tables back so people could evaluate `Collections.Pooled` without running BDN. It will reduce entrance price of evaluation and increase possibility of usage.  I, and other devs, seems jsut will look into table and feel safe to use  `Collections.Pooled`. I.e. `Collections.Pooled is same good, but with benefits. So mostly win if use instead of trade offs`.

**Comment by jtmueller** [comment]
Okay. Re-running all the benchmarks takes about six hours, but since I'm going to be doing that anyway after your ThrowHelper find, I'll be sure to put the memory analysis back in to the benchmarks that don't have it before I do so.
